---
- name: Stop the systemd service.
  systemd:
    state: stopped
    name: "syncthing@{{ syncthing_user }}.service"
  changed_when: false
  become: true

- name: Change the GUI listen address.
  community.general.xml:
    path: "{{ syncthing_user_result.home }}/.config/syncthing/config.xml"
    xpath: /configuration/gui/address
    value: "{{ syncthing_address }}"
  become: true

# - name: Change TLS setting.
#   community.general.xml:
#     path: "{{ syncthing_user_result.home }}/.config/syncthing/config.xml"
#     xpath: /configuration/gui/@tls
#     value: "{{ syncthing_tls }}"

- name: Start the systemd service.
  systemd:
    state: started
    name: "syncthing@{{ syncthing_user }}.service"
  changed_when: false
  become: true
