---
- name: Execute distribution dependent setup.
  include_tasks: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_distribution|lower }}-{{ ansible_distribution_major_version|lower }}.yml"
        - "{{ ansible_distribution|lower }}.yml"
        - "{{ ansible_os_family|lower }}.yml"
      skip: "{{ skip_unsupported_os }}"

- name: Create the syncthing user.
  user:
    name: "{{ syncthing_user }}"
    create_home: true
  register: syncthing_user_result
  become: true

- name: Enable the systemd service.
  systemd:
    state: started
    daemon_reload: true
    enabled: true
    name: "syncthing@{{ syncthing_user }}.service"
  become: true

- name: Configure syncthing instance.
  include_tasks: config.yml
