---
name: Continuous Integration
"on":
  pull_request:
  push:
  schedule:
    - cron: "0 6 * * 5"

defaults:
  run:
    working-directory: "stegmannb.syncthing"

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel an already running workflow.
        uses: fkirc/skip-duplicate-actions@master

      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2

      - uses: pre-commit/action@v2.0.0

  molecule:
    needs:
      - pre-commit
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distro:
          - ubuntu2004
          - debian10
    steps:
      - name: Cancel an already running workflow.
        uses: fkirc/skip-duplicate-actions@master

      - name: Check out the codebase.
        uses: actions/checkout@v2
        with:
          path: "stegmannb.syncthing"

      - name: Molecule
        uses: gofrolist/molecule-action@v2
        with:
          molecule_command: test
          molecule_working_dir: "stegmannb.syncthing"
        env:
          PY_COLORS: "1"
          ANSIBLE_FORCE_COLOR: "1"
          MOLECULE_DISTRO: ${{ matrix.distro }}
